[package]
name = "cerbere"
version = "0.1.0"
edition = "2024"

[dependencies]
crossterm = "0.29.0"
nix = { version = "0.30.1", features = ["user", "process"] }
pam = "0.8.0"
ratatui = "0.30.0"
pistis = { git = "https://github.com/VirgileHenry/pistis" }
